package constants

var (
	Analysisconfigerrs                                           = "analysis config err: %s"
	Notsupported                                                 = "not_supported"
	Hostuserpostgrespasswordpassportdbnamepostgressslmodedisable = "host=127.0.0.1 user=postgres password=password port=5432 dbname=postgres sslmode=disable"
	Providerpulltableerrors                                      = "provider pull table error: %s"
	VERCELAPITOKEN                                               = "VERCEL_API_TOKEN"
	VERCELTEAM                                                   = "VERCEL_TEAM"
	Newclientserrs                                               = "new clients err: %s"
	Constants_2                                                  = "*"
	Initprovidererrors                                           = "init provider error: %s"
	Constants_5                                                  = ""
	Constants_6                                                  = ""
	V                                                            = "v0.0.1"
	Constants_0                                                  = ""
	NA                                                           = "N/A"
	Testing                                                      = "testing"
	Constants_4                                                  = ""
	Apitokenmustbeconfigured                                     = "api_token must be configured"
	Errors                                                       = "errors"
	Constants_3                                                  = ""
	Context                                                      = "context"
	Vercel                                                       = "vercel"
	Accountinformationnotfound                                   = "account information not found"
	Os                                                           = "os"
	SELEFRADATABASEDSN                                           = "SELEFRA_DATABASE_DSN"
	Constants_1                                                  = "."
)
